### ISSUE TITLE
Password does not work with XMLRPC (WordPress Android App) ?

### ISSUE THREAD

**Issue by seboss666** [georgestephanis/application-passwords#91]
Hello,

I've configured Two-Factor with great success at the first try, but I also need access for the WordPress Android App that I use in train to work on drafts. After digging a little I found that addon, installed it and generated the password. But it does not work, I keep getting authentication errors on my phone.
My Setup : 
WordPress 4.9.10
PHP 7.0.33 (yes I know, upgrade is in testing process)

No errors in dedicated php_error log nor nginx's access or error log are to be seen. I've tried using it with and without spaces as it's shown et creation, I've retried to type it multiple times to prevent input mistakes (digital onscreen keyboards have really small keys for my fingers).

Digging a little, I've tried testing with curl. The REST API does work, but not XMLRPC that the Android app uses : 
```bash
$ curl --user "seboss666:4spXXXXXXXXXXXB" -X POST -d "title=New Title" https://blog.seboss666.info/wp-json/wp/v2/posts/5900
{"id":5900,"date":"2019-08-20T17:40:57","date_gmt":"2019-08-20T15:40:57","guid":{"rendered":"https:\/\/blog.seboss666.info\/?p=5900","raw":"https:\/\/blog.seboss666.info\/?p=5900"},"modified":"2019-08-20T17:40:57","modified_gmt":"2019-08-20T15:40:57","password":"","slug":"","status":"draft","type":"post","link":"https:\/\/blog.seboss666.info\/?p=5900","title":{"raw":"New Title","rendered":"New Title"},"content":...}}

$ curl -H 'Content-Type: text/xml' -d '<methodCall><methodName>wp.getUsers</methodName><params><param><value>1</value></param><param><value>seboss666</value></param><param><value>4spXXXXXXXXXXXB</value></param></params></methodCall>' https://blog.seboss666.info/xmlrpc.php
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <fault>
    <value>
      <struct>
        <member>
          <name>faultCode</name>
          <value><int>403</int></value>
        </member>
        <member>
          <name>faultString</name>
          <value><string>Identifiant ou mot de passe incorrect.</string></value>
        </member>
      </struct>
    </value>
  </fault>
</methodResponse>
```
As it was still working the morning just before I set up the Two-Factor addon, I'm pretty sure it's not one of my manipulations that "disabled" XMLRPC. Can you help me find where can be the problem ?

Thanks.

**Comment by seboss666** [comment]
Complement : For now I've disabled Two-Factor plugin, but letting the "Application Passwords" activated gave the Android App the access I was trying to get. But it's useless without Two-Factor, so how can this happen ?

**Comment by kasparsd** [comment]
Yes, this is due to a recent feature added to the Two-Factor plugin https://github.com/georgestephanis/two-factor/pull/271 which disables all password-based API-level authentication requests for users that have the two-factor enabled.

To allow any kind of password authentication for users with two-factor enabled, add the following filter:

```php
add_filter( 'two_factor_user_api_login_enable', '__return_true' ); 
```

which disables the [lockdown](https://github.com/georgestephanis/two-factor/blob/2f49d267cffc63f30664a6fc1863fa9c54d5ac84/class.two-factor-core.php#L272-L274).

**Comment by seboss666** [comment]
Hello, filter works but not completely as I wanted, as the "original" password is still usable from the app, so application password is useless in this case. How can I be sure that only application password is used without two-factor in XMLRPC ?

**Comment by alexclst** [comment]
I agree with @seboss666. Ideally the main password would not work but app passwords would when using XMLRPC or the API. As such, the mentioned filter is **not** a fix. What we need is these two plugins to work together so that app passwords can work for the API, but normal passwords will not. This is the point of app passwords anyway, to work for things like XMLRPC and the API, but main passwords not to, when two factor is enabled.
